### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [Nokse22/mini-text#1]
The current summary `A very small and minimalistic text view` isn't great (too long, starts with an article, not a call to action).

An easy improvement would be something like `Minimalistic text view`, but it'd be even better if the summary advertised the kinds of use cases you have in mind for the app.

An exercise that can help here is completing this sentence:

`Mini Text is an app that lets you "SUMMARY"`

Example from another app: `Clairvoyant is an app that lets you “Ask questions, get psychic answers”`

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by Nokse22** [comment]
Thank you for your feedback, I will improve it.
