### ISSUE TITLE
Feature Request: `Add buttons to increase and decrease the size of the text`

### ISSUE THREAD

**Issue by soumyaDghosh** [Nokse22/mini-text#11]
Hi, Can you add buttons in the app that can allow the app to increase or decrease the text sizes. It's very useful when reading in maximized mode

**Comment by Nokse22** [comment]
It' not really meant to be used in maximised mode, but there are ctrl+ and ctrl- shortcuts to increase and decrease the font size. I would prefer not to add too many buttons to the interface, but I'm thinking of adding at least a menu to access a settings page or something else.

**Comment by meybonomme** [comment]
> ...but I'm thinking of adding at least a menu to access a settings page or something else.

I like your app minimalistic concept, but I think "hamburger" menu is must be. At least "About" and "Keyboard shortcuts" menu items are needed. For now app and developer are pretty much anonymous and nobody can't see these workink keyboard shortcuts combos to increase or decrease font size. In my opinion "hamburger" menu doesn't hurt significantly apps minimalistic look and concept.

**Comment by meybonomme** [comment]
> @meybonomme The hamburger menu it's shown in the app layout when it's bigger.

Yes, of course, my mistake. Thank You for the answer!
