### ISSUE TITLE
Keyboard shortcut to increase font size not working as expected

### ISSUE THREAD

**Issue by sonicdes** [Nokse22/mini-text#13]
Hello! On my keyboard pressing Ctrl+"+" does not increase the font size. If I also hold down the Shift key, it works. I believe pressing "+" without shift leads to the keypress registering as "=".
I'm not sure what's the proper Gnome way to handle this, but maybe Ctrl+"=" key combination should trigger font size increase.

**Comment by Nokse22** [comment]
Hello. If on your keyboard you need to press shift+= to get the plus sign it is probably it. I'm assuming then that whenever there is a Ctrl+minus/plus shortcut you expect to be able to press the = button without shift, right? In that case I can add Ctrl+= to do the same as Ctrl+plus

**Comment by sonicdes** [comment]
Yes, that's correct. Would be thankful if you added that.
