### ISSUE TITLE
The icon doesn't look right 

### ISSUE THREAD

**Issue by kael-lillaj** [Nokse22/mini-text#26]
i'm on Debian 12, KDE Plasma 5.27.5 and the icon doesn't look right 
The icon theme is the default Breeze

![image](https://github.com/Nokse22/mini-text/assets/168609396/8ed3660f-a323-4991-ae06-8d9f994bcd85)

**Comment by Nokse22** [comment]
That is strange, but I don't think it's a problem with the app since I haven't done anything different from other apps.
