### ISSUE TITLE
Feature request: Lunch with loaded text

### ISSUE THREAD

**Issue by slarrain** [Nokse22/mini-text#37]
I think it would be awesome -and perhaps not that difficult- to be able to lunch Mini-Text with text already on it. Say, for example, we have a file full of inspirational quotes, and we would like to have a bash script lunch Mini Text with a quote for some time and then replace it with another, programmatically.

Would something like that be possible?

**Comment by Nokse22** [comment]
Hi! I can add support for opening a file using Mini Text and loading the content into it, but I don't really know how you could achieve changing it's content after some time.

**Comment by slarrain** [comment]
Interesting. Perhaps we would need to close it and launch it again.
If your are at it, I think it should probably need to be able to load the content of a file but also of StdIn.
This way, we could write a bash script that parses a "quote" file, and opens MiniText with a quote for some time, closes it and does it again with the next line or something.
Do you think that something like that would be possible?
Many thanks.

**Comment by Nokse22** [comment]
I think it would be best to make an app specifically for this use case and keep MiniText simple. If you want to suggest it you can do so here: https://gitlab.gnome.org/bertob/app-ideas/-/issues

**Comment by slarrain** [comment]
I understand. I thought it could be an interesting use case for Mini Text, but it is your App. Thank you for your replies.
Closing the issue.
