### ISSUE TITLE
Dark Mode Not Applying on Ubuntu 20.04

### ISSUE THREAD

**Issue by TroelsS** [Nokse22/mini-text#5]
**Description:**
I am using Ubuntu 20.04 and have set the system appearance to use the Dark window colors. However, when I open Minitext, the application interface remains in the "white" mode, failing to switch to the Dark mode as expected.

Steps to Reproduce:

1.    Install Minitext on Ubuntu 20.04.
2.    Set the system appearance to use Dark window colors.
3.   Open Minitext.

**Expected Behavior:**
When the system appearance is set to Dark window colors, Minitext should automatically switch to Dark mode, reflecting the system-wide appearance settings.

**Actual Behavior:**
Minitext remains in the "white" mode, regardless of the system appearance settings.

**Additional Information:**
Ubuntu Version: 20.04.6
Minitext Version: 0.1.7
System Appearance Settings: Dark window colors

**Possible Workarounds:**
If there are any known workarounds or settings adjustments that users can try in order to enable Dark mode in Minitext, please provide them here.

This issue impacts the usability and consistency of the application with the system-wide appearance settings. It would be greatly appreciated if the Minitext development team could address this matter and provide a fix or guidance on how to enable Dark mode when the system appearance is set to Dark.

Thank you for your attention to this matter.

**Comment by Nokse22** [comment]
Hi, this is most probably an issue with Ubuntu because it uses a custom theme. Look at [this](https://ubuntuhandbook.org/index.php/2021/10/enable-dark-flatpak-apps-ubuntu-linux-mint/) article for how to install the Ubuntu dark theme. Basically you need to run `flatpak install flathub org.gtk.Gtk3theme.Yaru-dark` to install the correct theme.

**Comment by TroelsS** [comment]
I have already installed the "org.gtk.Gtk3theme.Yaru-dark" theme, so this isn't having any effect. Is there something else I need to do or consider to make it work properly? Your assistance is greatly appreciated.

**Comment by Nokse22** [comment]
I found a way to make the app use the dark theme. You need to install [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and in the "all applications" section (or the minitext section, but will applied only to that app) you need to add these permissions, this way all flatpaks will use the dark theme, I couldn't find a way to make the app follow the system theme if changed. 

![Screenshot from 2023-08-12 21-19-21](https://github.com/Nokse22/mini-text/assets/44558032/867fa165-504a-4b58-9d05-9a6758714a66)

**Comment by TroelsS** [comment]
This works perfectly, thank you for your response.
